// Code generated by MockGen. DO NOT EDIT.
// Source: ethapi_backend.go
//
// Generated by this command:
//
//	mockgen -source=ethapi_backend.go -destination=ethapi_backend_mock.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockforceableEmitter is a mock of forceableEmitter interface.
type MockforceableEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockforceableEmitterMockRecorder
	isgomock struct{}
}

// MockforceableEmitterMockRecorder is the mock recorder for MockforceableEmitter.
type MockforceableEmitterMockRecorder struct {
	mock *MockforceableEmitter
}

// NewMockforceableEmitter creates a new mock instance.
func NewMockforceableEmitter(ctrl *gomock.Controller) *MockforceableEmitter {
	mock := &MockforceableEmitter{ctrl: ctrl}
	mock.recorder = &MockforceableEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockforceableEmitter) EXPECT() *MockforceableEmitterMockRecorder {
	return m.recorder
}

// ForceEventEmissionForTesting mocks base method.
func (m *MockforceableEmitter) ForceEventEmissionForTesting(txs []*types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceEventEmissionForTesting", txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceEventEmissionForTesting indicates an expected call of ForceEventEmissionForTesting.
func (mr *MockforceableEmitterMockRecorder) ForceEventEmissionForTesting(txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceEventEmissionForTesting", reflect.TypeOf((*MockforceableEmitter)(nil).ForceEventEmissionForTesting), txs)
}
