// Code generated by MockGen. DO NOT EDIT.
// Source: table_test.go
//
// Generated by this command:
//
//	mockgen -source=table_test.go -destination=table_mock.go -package=gossip
//

// Package gossip is a generated GoMock package.
package gossip

import (
	reflect "reflect"

	kvdb "github.com/Fantom-foundation/lachesis-base/kvdb"
	gomock "go.uber.org/mock/gomock"
)

// MockstoreTable is a mock of storeTable interface.
type MockstoreTable struct {
	ctrl     *gomock.Controller
	recorder *MockstoreTableMockRecorder
	isgomock struct{}
}

// MockstoreTableMockRecorder is the mock recorder for MockstoreTable.
type MockstoreTableMockRecorder struct {
	mock *MockstoreTable
}

// NewMockstoreTable creates a new mock instance.
func NewMockstoreTable(ctrl *gomock.Controller) *MockstoreTable {
	mock := &MockstoreTable{ctrl: ctrl}
	mock.recorder = &MockstoreTableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstoreTable) EXPECT() *MockstoreTableMockRecorder {
	return m.recorder
}

// AncientDatadir mocks base method.
func (m *MockstoreTable) AncientDatadir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AncientDatadir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AncientDatadir indicates an expected call of AncientDatadir.
func (mr *MockstoreTableMockRecorder) AncientDatadir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AncientDatadir", reflect.TypeOf((*MockstoreTable)(nil).AncientDatadir))
}

// Close mocks base method.
func (m *MockstoreTable) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockstoreTableMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockstoreTable)(nil).Close))
}

// Compact mocks base method.
func (m *MockstoreTable) Compact(start, limit []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", start, limit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockstoreTableMockRecorder) Compact(start, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockstoreTable)(nil).Compact), start, limit)
}

// Delete mocks base method.
func (m *MockstoreTable) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockstoreTableMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockstoreTable)(nil).Delete), key)
}

// Drop mocks base method.
func (m *MockstoreTable) Drop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Drop")
}

// Drop indicates an expected call of Drop.
func (mr *MockstoreTableMockRecorder) Drop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockstoreTable)(nil).Drop))
}

// Get mocks base method.
func (m *MockstoreTable) Get(key []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockstoreTableMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockstoreTable)(nil).Get), key)
}

// GetSnapshot mocks base method.
func (m *MockstoreTable) GetSnapshot() (kvdb.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot")
	ret0, _ := ret[0].(kvdb.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockstoreTableMockRecorder) GetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockstoreTable)(nil).GetSnapshot))
}

// Has mocks base method.
func (m *MockstoreTable) Has(key []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockstoreTableMockRecorder) Has(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockstoreTable)(nil).Has), key)
}

// NewBatch mocks base method.
func (m *MockstoreTable) NewBatch() kvdb.Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBatch")
	ret0, _ := ret[0].(kvdb.Batch)
	return ret0
}

// NewBatch indicates an expected call of NewBatch.
func (mr *MockstoreTableMockRecorder) NewBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBatch", reflect.TypeOf((*MockstoreTable)(nil).NewBatch))
}

// NewIterator mocks base method.
func (m *MockstoreTable) NewIterator(prefix, start []byte) kvdb.Iterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIterator", prefix, start)
	ret0, _ := ret[0].(kvdb.Iterator)
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockstoreTableMockRecorder) NewIterator(prefix, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockstoreTable)(nil).NewIterator), prefix, start)
}

// Put mocks base method.
func (m *MockstoreTable) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockstoreTableMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockstoreTable)(nil).Put), key, value)
}

// Stat mocks base method.
func (m *MockstoreTable) Stat() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockstoreTableMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockstoreTable)(nil).Stat))
}

// MockstoreBatch is a mock of storeBatch interface.
type MockstoreBatch struct {
	ctrl     *gomock.Controller
	recorder *MockstoreBatchMockRecorder
	isgomock struct{}
}

// MockstoreBatchMockRecorder is the mock recorder for MockstoreBatch.
type MockstoreBatchMockRecorder struct {
	mock *MockstoreBatch
}

// NewMockstoreBatch creates a new mock instance.
func NewMockstoreBatch(ctrl *gomock.Controller) *MockstoreBatch {
	mock := &MockstoreBatch{ctrl: ctrl}
	mock.recorder = &MockstoreBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstoreBatch) EXPECT() *MockstoreBatchMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockstoreBatch) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockstoreBatchMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockstoreBatch)(nil).Close))
}

// Delete mocks base method.
func (m *MockstoreBatch) Delete(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockstoreBatchMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockstoreBatch)(nil).Delete), key)
}

// DeleteRange mocks base method.
func (m *MockstoreBatch) DeleteRange(start, end []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRange", start, end)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRange indicates an expected call of DeleteRange.
func (mr *MockstoreBatchMockRecorder) DeleteRange(start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRange", reflect.TypeOf((*MockstoreBatch)(nil).DeleteRange), start, end)
}

// Put mocks base method.
func (m *MockstoreBatch) Put(key, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockstoreBatchMockRecorder) Put(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockstoreBatch)(nil).Put), key, value)
}

// Replay mocks base method.
func (m *MockstoreBatch) Replay(w kvdb.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replay", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replay indicates an expected call of Replay.
func (mr *MockstoreBatchMockRecorder) Replay(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replay", reflect.TypeOf((*MockstoreBatch)(nil).Replay), w)
}

// Reset mocks base method.
func (m *MockstoreBatch) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockstoreBatchMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockstoreBatch)(nil).Reset))
}

// ValueSize mocks base method.
func (m *MockstoreBatch) ValueSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// ValueSize indicates an expected call of ValueSize.
func (mr *MockstoreBatchMockRecorder) ValueSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueSize", reflect.TypeOf((*MockstoreBatch)(nil).ValueSize))
}

// Write mocks base method.
func (m *MockstoreBatch) Write() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write")
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockstoreBatchMockRecorder) Write() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockstoreBatch)(nil).Write))
}

// MockdbIterator is a mock of dbIterator interface.
type MockdbIterator struct {
	ctrl     *gomock.Controller
	recorder *MockdbIteratorMockRecorder
	isgomock struct{}
}

// MockdbIteratorMockRecorder is the mock recorder for MockdbIterator.
type MockdbIteratorMockRecorder struct {
	mock *MockdbIterator
}

// NewMockdbIterator creates a new mock instance.
func NewMockdbIterator(ctrl *gomock.Controller) *MockdbIterator {
	mock := &MockdbIterator{ctrl: ctrl}
	mock.recorder = &MockdbIteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbIterator) EXPECT() *MockdbIteratorMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockdbIterator) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockdbIteratorMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockdbIterator)(nil).Error))
}

// Key mocks base method.
func (m *MockdbIterator) Key() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Key indicates an expected call of Key.
func (mr *MockdbIteratorMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockdbIterator)(nil).Key))
}

// Next mocks base method.
func (m *MockdbIterator) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockdbIteratorMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockdbIterator)(nil).Next))
}

// Release mocks base method.
func (m *MockdbIterator) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockdbIteratorMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockdbIterator)(nil).Release))
}

// Value mocks base method.
func (m *MockdbIterator) Value() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockdbIteratorMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockdbIterator)(nil).Value))
}
