// Code generated by MockGen. DO NOT EDIT.
// Source: block_metrics.go
//
// Generated by this command:
//
//	mockgen -source=block_metrics.go -destination=block_metrics_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlockExecutionMetrics is a mock of BlockExecutionMetrics interface.
type MockBlockExecutionMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockBlockExecutionMetricsMockRecorder
	isgomock struct{}
}

// MockBlockExecutionMetricsMockRecorder is the mock recorder for MockBlockExecutionMetrics.
type MockBlockExecutionMetricsMockRecorder struct {
	mock *MockBlockExecutionMetrics
}

// NewMockBlockExecutionMetrics creates a new mock instance.
func NewMockBlockExecutionMetrics(ctrl *gomock.Controller) *MockBlockExecutionMetrics {
	mock := &MockBlockExecutionMetrics{ctrl: ctrl}
	mock.recorder = &MockBlockExecutionMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockExecutionMetrics) EXPECT() *MockBlockExecutionMetricsMockRecorder {
	return m.recorder
}

// IncExecutedBundle mocks base method.
func (m *MockBlockExecutionMetrics) IncExecutedBundle() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncExecutedBundle")
}

// IncExecutedBundle indicates an expected call of IncExecutedBundle.
func (mr *MockBlockExecutionMetricsMockRecorder) IncExecutedBundle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncExecutedBundle", reflect.TypeOf((*MockBlockExecutionMetrics)(nil).IncExecutedBundle))
}

// IncInvalidBundle mocks base method.
func (m *MockBlockExecutionMetrics) IncInvalidBundle() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncInvalidBundle")
}

// IncInvalidBundle indicates an expected call of IncInvalidBundle.
func (mr *MockBlockExecutionMetricsMockRecorder) IncInvalidBundle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncInvalidBundle", reflect.TypeOf((*MockBlockExecutionMetrics)(nil).IncInvalidBundle))
}

// IncRolledBackBundle mocks base method.
func (m *MockBlockExecutionMetrics) IncRolledBackBundle() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRolledBackBundle")
}

// IncRolledBackBundle indicates an expected call of IncRolledBackBundle.
func (mr *MockBlockExecutionMetricsMockRecorder) IncRolledBackBundle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRolledBackBundle", reflect.TypeOf((*MockBlockExecutionMetrics)(nil).IncRolledBackBundle))
}

// IncSkippedSponsoredTx mocks base method.
func (m *MockBlockExecutionMetrics) IncSkippedSponsoredTx() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncSkippedSponsoredTx")
}

// IncSkippedSponsoredTx indicates an expected call of IncSkippedSponsoredTx.
func (mr *MockBlockExecutionMetricsMockRecorder) IncSkippedSponsoredTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncSkippedSponsoredTx", reflect.TypeOf((*MockBlockExecutionMetrics)(nil).IncSkippedSponsoredTx))
}

// IncSponsoredTx mocks base method.
func (m *MockBlockExecutionMetrics) IncSponsoredTx() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncSponsoredTx")
}

// IncSponsoredTx indicates an expected call of IncSponsoredTx.
func (mr *MockBlockExecutionMetricsMockRecorder) IncSponsoredTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncSponsoredTx", reflect.TypeOf((*MockBlockExecutionMetrics)(nil).IncSponsoredTx))
}

// ObserveBundleEfficiency mocks base method.
func (m *MockBlockExecutionMetrics) ObserveBundleEfficiency(usedGas, totalExecGas uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveBundleEfficiency", usedGas, totalExecGas)
}

// ObserveBundleEfficiency indicates an expected call of ObserveBundleEfficiency.
func (mr *MockBlockExecutionMetricsMockRecorder) ObserveBundleEfficiency(usedGas, totalExecGas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveBundleEfficiency", reflect.TypeOf((*MockBlockExecutionMetrics)(nil).ObserveBundleEfficiency), usedGas, totalExecGas)
}
