// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_precheck.go
//
// Generated by this command:
//
//	mockgen -source=bundle_precheck.go -destination=bundle_precheck_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	reflect "reflect"

	state "github.com/0xsoniclabs/sonic/inter/state"
	opera "github.com/0xsoniclabs/sonic/opera"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	params "github.com/ethereum/go-ethereum/params"
	gomock "go.uber.org/mock/gomock"
)

// MockChainStateForBundleEval is a mock of ChainStateForBundleEval interface.
type MockChainStateForBundleEval struct {
	ctrl     *gomock.Controller
	recorder *MockChainStateForBundleEvalMockRecorder
	isgomock struct{}
}

// MockChainStateForBundleEvalMockRecorder is the mock recorder for MockChainStateForBundleEval.
type MockChainStateForBundleEvalMockRecorder struct {
	mock *MockChainStateForBundleEval
}

// NewMockChainStateForBundleEval creates a new mock instance.
func NewMockChainStateForBundleEval(ctrl *gomock.Controller) *MockChainStateForBundleEval {
	mock := &MockChainStateForBundleEval{ctrl: ctrl}
	mock.recorder = &MockChainStateForBundleEvalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainStateForBundleEval) EXPECT() *MockChainStateForBundleEvalMockRecorder {
	return m.recorder
}

// GetCurrentChainConfig mocks base method.
func (m *MockChainStateForBundleEval) GetCurrentChainConfig() *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentChainConfig")
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// GetCurrentChainConfig indicates an expected call of GetCurrentChainConfig.
func (mr *MockChainStateForBundleEvalMockRecorder) GetCurrentChainConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentChainConfig", reflect.TypeOf((*MockChainStateForBundleEval)(nil).GetCurrentChainConfig))
}

// GetCurrentNetworkRules mocks base method.
func (m *MockChainStateForBundleEval) GetCurrentNetworkRules() opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentNetworkRules")
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetCurrentNetworkRules indicates an expected call of GetCurrentNetworkRules.
func (mr *MockChainStateForBundleEvalMockRecorder) GetCurrentNetworkRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentNetworkRules", reflect.TypeOf((*MockChainStateForBundleEval)(nil).GetCurrentNetworkRules))
}

// GetLatestHeader mocks base method.
func (m *MockChainStateForBundleEval) GetLatestHeader() *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestHeader")
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// GetLatestHeader indicates an expected call of GetLatestHeader.
func (mr *MockChainStateForBundleEvalMockRecorder) GetLatestHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestHeader", reflect.TypeOf((*MockChainStateForBundleEval)(nil).GetLatestHeader))
}

// Header mocks base method.
func (m *MockChainStateForBundleEval) Header(hash common.Hash, number uint64) *EvmHeader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", hash, number)
	ret0, _ := ret[0].(*EvmHeader)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockChainStateForBundleEvalMockRecorder) Header(hash, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockChainStateForBundleEval)(nil).Header), hash, number)
}

// MockNonceSource is a mock of NonceSource interface.
type MockNonceSource struct {
	ctrl     *gomock.Controller
	recorder *MockNonceSourceMockRecorder
	isgomock struct{}
}

// MockNonceSourceMockRecorder is the mock recorder for MockNonceSource.
type MockNonceSourceMockRecorder struct {
	mock *MockNonceSource
}

// NewMockNonceSource creates a new mock instance.
func NewMockNonceSource(ctrl *gomock.Controller) *MockNonceSource {
	mock := &MockNonceSource{ctrl: ctrl}
	mock.recorder = &MockNonceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceSource) EXPECT() *MockNonceSourceMockRecorder {
	return m.recorder
}

// GetNonce mocks base method.
func (m *MockNonceSource) GetNonce(addr common.Address) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", addr)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockNonceSourceMockRecorder) GetNonce(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockNonceSource)(nil).GetNonce), addr)
}

// MocktransactionProcessorFactory is a mock of transactionProcessorFactory interface.
type MocktransactionProcessorFactory struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionProcessorFactoryMockRecorder
	isgomock struct{}
}

// MocktransactionProcessorFactoryMockRecorder is the mock recorder for MocktransactionProcessorFactory.
type MocktransactionProcessorFactoryMockRecorder struct {
	mock *MocktransactionProcessorFactory
}

// NewMocktransactionProcessorFactory creates a new mock instance.
func NewMocktransactionProcessorFactory(ctrl *gomock.Controller) *MocktransactionProcessorFactory {
	mock := &MocktransactionProcessorFactory{ctrl: ctrl}
	mock.recorder = &MocktransactionProcessorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionProcessorFactory) EXPECT() *MocktransactionProcessorFactoryMockRecorder {
	return m.recorder
}

// newTransactionProcessor mocks base method.
func (m *MocktransactionProcessorFactory) newTransactionProcessor(arg0 ChainState, arg1 state.StateDB, arg2 *EvmBlock) transactionProcessor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "newTransactionProcessor", arg0, arg1, arg2)
	ret0, _ := ret[0].(transactionProcessor)
	return ret0
}

// newTransactionProcessor indicates an expected call of newTransactionProcessor.
func (mr *MocktransactionProcessorFactoryMockRecorder) newTransactionProcessor(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "newTransactionProcessor", reflect.TypeOf((*MocktransactionProcessorFactory)(nil).newTransactionProcessor), arg0, arg1, arg2)
}

// MocktransactionProcessor is a mock of transactionProcessor interface.
type MocktransactionProcessor struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionProcessorMockRecorder
	isgomock struct{}
}

// MocktransactionProcessorMockRecorder is the mock recorder for MocktransactionProcessor.
type MocktransactionProcessorMockRecorder struct {
	mock *MocktransactionProcessor
}

// NewMocktransactionProcessor creates a new mock instance.
func NewMocktransactionProcessor(ctrl *gomock.Controller) *MocktransactionProcessor {
	mock := &MocktransactionProcessor{ctrl: ctrl}
	mock.recorder = &MocktransactionProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionProcessor) EXPECT() *MocktransactionProcessorMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MocktransactionProcessor) Run(arg0 int, arg1 *types.Transaction) ProcessSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(ProcessSummary)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MocktransactionProcessorMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MocktransactionProcessor)(nil).Run), arg0, arg1)
}

// MockBundleEvaluator is a mock of BundleEvaluator interface.
type MockBundleEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockBundleEvaluatorMockRecorder
	isgomock struct{}
}

// MockBundleEvaluatorMockRecorder is the mock recorder for MockBundleEvaluator.
type MockBundleEvaluatorMockRecorder struct {
	mock *MockBundleEvaluator
}

// NewMockBundleEvaluator creates a new mock instance.
func NewMockBundleEvaluator(ctrl *gomock.Controller) *MockBundleEvaluator {
	mock := &MockBundleEvaluator{ctrl: ctrl}
	mock.recorder = &MockBundleEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleEvaluator) EXPECT() *MockBundleEvaluatorMockRecorder {
	return m.recorder
}

// GetBundleState mocks base method.
func (m *MockBundleEvaluator) GetBundleState(chain ChainStateForBundleEval, stateDb state.StateDB, envelope *types.Transaction) BundleState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBundleState", chain, stateDb, envelope)
	ret0, _ := ret[0].(BundleState)
	return ret0
}

// GetBundleState indicates an expected call of GetBundleState.
func (mr *MockBundleEvaluatorMockRecorder) GetBundleState(chain, stateDb, envelope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBundleState", reflect.TypeOf((*MockBundleEvaluator)(nil).GetBundleState), chain, stateDb, envelope)
}
