// Code generated by MockGen. DO NOT EDIT.
// Source: tx_validation.go
//
// Generated by this command:
//
//	mockgen -source=tx_validation.go -destination=tx_validation_mock.go -package=evmcore
//

// Package evmcore is a generated GoMock package.
package evmcore

import (
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSigner is a mock of Signer interface.
type MockSigner struct {
	ctrl     *gomock.Controller
	recorder *MockSignerMockRecorder
	isgomock struct{}
}

// MockSignerMockRecorder is the mock recorder for MockSigner.
type MockSignerMockRecorder struct {
	mock *MockSigner
}

// NewMockSigner creates a new mock instance.
func NewMockSigner(ctrl *gomock.Controller) *MockSigner {
	mock := &MockSigner{ctrl: ctrl}
	mock.recorder = &MockSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSigner) EXPECT() *MockSignerMockRecorder {
	return m.recorder
}

// ChainID mocks base method.
func (m *MockSigner) ChainID() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// ChainID indicates an expected call of ChainID.
func (mr *MockSignerMockRecorder) ChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockSigner)(nil).ChainID))
}

// Equal mocks base method.
func (m *MockSigner) Equal(arg0 types.Signer) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Equal", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Equal indicates an expected call of Equal.
func (mr *MockSignerMockRecorder) Equal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Equal", reflect.TypeOf((*MockSigner)(nil).Equal), arg0)
}

// Hash mocks base method.
func (m *MockSigner) Hash(tx *types.Transaction) common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", tx)
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockSignerMockRecorder) Hash(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockSigner)(nil).Hash), tx)
}

// Sender mocks base method.
func (m *MockSigner) Sender(tx *types.Transaction) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sender", tx)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sender indicates an expected call of Sender.
func (mr *MockSignerMockRecorder) Sender(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sender", reflect.TypeOf((*MockSigner)(nil).Sender), tx)
}

// SignatureValues mocks base method.
func (m *MockSigner) SignatureValues(tx *types.Transaction, sig []byte) (*big.Int, *big.Int, *big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignatureValues", tx, sig)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(*big.Int)
	ret2, _ := ret[2].(*big.Int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// SignatureValues indicates an expected call of SignatureValues.
func (mr *MockSignerMockRecorder) SignatureValues(tx, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignatureValues", reflect.TypeOf((*MockSigner)(nil).SignatureValues), tx, sig)
}

// MocktxValidationTarget is a mock of txValidationTarget interface.
type MocktxValidationTarget struct {
	ctrl     *gomock.Controller
	recorder *MocktxValidationTargetMockRecorder
	isgomock struct{}
}

// MocktxValidationTargetMockRecorder is the mock recorder for MocktxValidationTarget.
type MocktxValidationTargetMockRecorder struct {
	mock *MocktxValidationTarget
}

// NewMocktxValidationTarget creates a new mock instance.
func NewMocktxValidationTarget(ctrl *gomock.Controller) *MocktxValidationTarget {
	mock := &MocktxValidationTarget{ctrl: ctrl}
	mock.recorder = &MocktxValidationTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxValidationTarget) EXPECT() *MocktxValidationTargetMockRecorder {
	return m.recorder
}

// BlobGasFeeCap mocks base method.
func (m *MocktxValidationTarget) BlobGasFeeCap() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobGasFeeCap")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// BlobGasFeeCap indicates an expected call of BlobGasFeeCap.
func (mr *MocktxValidationTargetMockRecorder) BlobGasFeeCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobGasFeeCap", reflect.TypeOf((*MocktxValidationTarget)(nil).BlobGasFeeCap))
}

// Cost mocks base method.
func (m *MocktxValidationTarget) Cost() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cost")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// Cost indicates an expected call of Cost.
func (mr *MocktxValidationTargetMockRecorder) Cost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cost", reflect.TypeOf((*MocktxValidationTarget)(nil).Cost))
}

// GasFeeCap mocks base method.
func (m *MocktxValidationTarget) GasFeeCap() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasFeeCap")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GasFeeCap indicates an expected call of GasFeeCap.
func (mr *MocktxValidationTargetMockRecorder) GasFeeCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasFeeCap", reflect.TypeOf((*MocktxValidationTarget)(nil).GasFeeCap))
}

// GasPrice mocks base method.
func (m *MocktxValidationTarget) GasPrice() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasPrice")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GasPrice indicates an expected call of GasPrice.
func (mr *MocktxValidationTargetMockRecorder) GasPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasPrice", reflect.TypeOf((*MocktxValidationTarget)(nil).GasPrice))
}

// GasTipCap mocks base method.
func (m *MocktxValidationTarget) GasTipCap() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasTipCap")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GasTipCap indicates an expected call of GasTipCap.
func (mr *MocktxValidationTargetMockRecorder) GasTipCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasTipCap", reflect.TypeOf((*MocktxValidationTarget)(nil).GasTipCap))
}

// Nonce mocks base method.
func (m *MocktxValidationTarget) Nonce() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nonce")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Nonce indicates an expected call of Nonce.
func (mr *MocktxValidationTargetMockRecorder) Nonce() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nonce", reflect.TypeOf((*MocktxValidationTarget)(nil).Nonce))
}

// SetCodeAuthorizations mocks base method.
func (m *MocktxValidationTarget) SetCodeAuthorizations() []types.SetCodeAuthorization {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCodeAuthorizations")
	ret0, _ := ret[0].([]types.SetCodeAuthorization)
	return ret0
}

// SetCodeAuthorizations indicates an expected call of SetCodeAuthorizations.
func (mr *MocktxValidationTargetMockRecorder) SetCodeAuthorizations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCodeAuthorizations", reflect.TypeOf((*MocktxValidationTarget)(nil).SetCodeAuthorizations))
}

// Type mocks base method.
func (m *MocktxValidationTarget) Type() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MocktxValidationTargetMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MocktxValidationTarget)(nil).Type))
}

// Value mocks base method.
func (m *MocktxValidationTarget) Value() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MocktxValidationTargetMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MocktxValidationTarget)(nil).Value))
}
