// Code generated by MockGen. DO NOT EDIT.
// Source: iterator.go
//
// Generated by this command:
//
//	mockgen -source=iterator.go -package=leap -destination=iterator_mock.go
//

// Package leap is a generated GoMock package.
package leap

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIterator is a mock of Iterator interface.
type MockIterator[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockIteratorMockRecorder[T]
	isgomock struct{}
}

// MockIteratorMockRecorder is the mock recorder for MockIterator.
type MockIteratorMockRecorder[T any] struct {
	mock *MockIterator[T]
}

// NewMockIterator creates a new mock instance.
func NewMockIterator[T any](ctrl *gomock.Controller) *MockIterator[T] {
	mock := &MockIterator[T]{ctrl: ctrl}
	mock.recorder = &MockIteratorMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIterator[T]) EXPECT() *MockIteratorMockRecorder[T] {
	return m.recorder
}

// Current mocks base method.
func (m *MockIterator[T]) Current() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(T)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockIteratorMockRecorder[T]) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockIterator[T])(nil).Current))
}

// Next mocks base method.
func (m *MockIterator[T]) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockIteratorMockRecorder[T]) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockIterator[T])(nil).Next))
}

// Release mocks base method.
func (m *MockIterator[T]) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockIteratorMockRecorder[T]) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockIterator[T])(nil).Release))
}

// Seek mocks base method.
func (m *MockIterator[T]) Seek(arg0 T) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Seek indicates an expected call of Seek.
func (mr *MockIteratorMockRecorder[T]) Seek(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockIterator[T])(nil).Seek), arg0)
}
