// Code generated by MockGen. DO NOT EDIT.
// Source: bundle_processor.go
//
// Generated by this command:
//
//	mockgen -source=bundle_processor.go -destination=bundle_processor_mock.go -package=bundle
//

// Package bundle is a generated GoMock package.
package bundle

import (
	reflect "reflect"

	core_types "github.com/0xsoniclabs/sonic/evmcore/core_types"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRunner is a mock of TransactionRunner interface.
type MockTransactionRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRunnerMockRecorder
	isgomock struct{}
}

// MockTransactionRunnerMockRecorder is the mock recorder for MockTransactionRunner.
type MockTransactionRunnerMockRecorder struct {
	mock *MockTransactionRunner
}

// NewMockTransactionRunner creates a new mock instance.
func NewMockTransactionRunner(ctrl *gomock.Controller) *MockTransactionRunner {
	mock := &MockTransactionRunner{ctrl: ctrl}
	mock.recorder = &MockTransactionRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRunner) EXPECT() *MockTransactionRunnerMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockTransactionRunner) CreateSnapshot() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot")
	ret0, _ := ret[0].(int)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockTransactionRunnerMockRecorder) CreateSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockTransactionRunner)(nil).CreateSnapshot))
}

// RevertToSnapshot mocks base method.
func (m *MockTransactionRunner) RevertToSnapshot(id int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevertToSnapshot", id)
}

// RevertToSnapshot indicates an expected call of RevertToSnapshot.
func (mr *MockTransactionRunnerMockRecorder) RevertToSnapshot(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertToSnapshot", reflect.TypeOf((*MockTransactionRunner)(nil).RevertToSnapshot), id)
}

// Run mocks base method.
func (m *MockTransactionRunner) Run(tx *types.Transaction) core_types.TransactionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", tx)
	ret0, _ := ret[0].(core_types.TransactionResult)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTransactionRunnerMockRecorder) Run(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTransactionRunner)(nil).Run), tx)
}
