// Code generated by MockGen. DO NOT EDIT.
// Source: execution_plan_visitor.go
//
// Generated by this command:
//
//	mockgen -source=execution_plan_visitor.go -destination=execution_plan_visitor_mock.go -package=bundle
//

// Package bundle is a generated GoMock package.
package bundle

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutionPlanVisitor is a mock of ExecutionPlanVisitor interface.
type MockExecutionPlanVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionPlanVisitorMockRecorder
	isgomock struct{}
}

// MockExecutionPlanVisitorMockRecorder is the mock recorder for MockExecutionPlanVisitor.
type MockExecutionPlanVisitorMockRecorder struct {
	mock *MockExecutionPlanVisitor
}

// NewMockExecutionPlanVisitor creates a new mock instance.
func NewMockExecutionPlanVisitor(ctrl *gomock.Controller) *MockExecutionPlanVisitor {
	mock := &MockExecutionPlanVisitor{ctrl: ctrl}
	mock.recorder = &MockExecutionPlanVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionPlanVisitor) EXPECT() *MockExecutionPlanVisitorMockRecorder {
	return m.recorder
}

// BeginGroup mocks base method.
func (m *MockExecutionPlanVisitor) BeginGroup(oneOf, tolerateFailed bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BeginGroup", oneOf, tolerateFailed)
}

// BeginGroup indicates an expected call of BeginGroup.
func (mr *MockExecutionPlanVisitorMockRecorder) BeginGroup(oneOf, tolerateFailed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginGroup", reflect.TypeOf((*MockExecutionPlanVisitor)(nil).BeginGroup), oneOf, tolerateFailed)
}

// EndGroup mocks base method.
func (m *MockExecutionPlanVisitor) EndGroup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndGroup")
}

// EndGroup indicates an expected call of EndGroup.
func (mr *MockExecutionPlanVisitorMockRecorder) EndGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndGroup", reflect.TypeOf((*MockExecutionPlanVisitor)(nil).EndGroup))
}

// Step mocks base method.
func (m *MockExecutionPlanVisitor) Step(flags ExecutionFlags, txRef TxReference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Step", flags, txRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Step indicates an expected call of Step.
func (mr *MockExecutionPlanVisitorMockRecorder) Step(flags, txRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Step", reflect.TypeOf((*MockExecutionPlanVisitor)(nil).Step), flags, txRef)
}
