// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=metrics_mock.go -package=utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsHistogram is a mock of MetricsHistogram interface.
type MockMetricsHistogram struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsHistogramMockRecorder
	isgomock struct{}
}

// MockMetricsHistogramMockRecorder is the mock recorder for MockMetricsHistogram.
type MockMetricsHistogramMockRecorder struct {
	mock *MockMetricsHistogram
}

// NewMockMetricsHistogram creates a new mock instance.
func NewMockMetricsHistogram(ctrl *gomock.Controller) *MockMetricsHistogram {
	mock := &MockMetricsHistogram{ctrl: ctrl}
	mock.recorder = &MockMetricsHistogramMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsHistogram) EXPECT() *MockMetricsHistogramMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockMetricsHistogram) Observe(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Observe", arg0)
}

// Observe indicates an expected call of Observe.
func (mr *MockMetricsHistogramMockRecorder) Observe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockMetricsHistogram)(nil).Observe), arg0)
}

// MockMetricsCounter is a mock of MetricsCounter interface.
type MockMetricsCounter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCounterMockRecorder
	isgomock struct{}
}

// MockMetricsCounterMockRecorder is the mock recorder for MockMetricsCounter.
type MockMetricsCounterMockRecorder struct {
	mock *MockMetricsCounter
}

// NewMockMetricsCounter creates a new mock instance.
func NewMockMetricsCounter(ctrl *gomock.Controller) *MockMetricsCounter {
	mock := &MockMetricsCounter{ctrl: ctrl}
	mock.recorder = &MockMetricsCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCounter) EXPECT() *MockMetricsCounterMockRecorder {
	return m.recorder
}

// Inc mocks base method.
func (m *MockMetricsCounter) Inc(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Inc", arg0)
}

// Inc indicates an expected call of Inc.
func (mr *MockMetricsCounterMockRecorder) Inc(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockMetricsCounter)(nil).Inc), arg0)
}
