// Code generated by MockGen. DO NOT EDIT.
// Source: carmen.go
//
// Generated by this command:
//
//	mockgen -source=carmen.go -destination=carmen_mock.go -package=evmstore
//

// Package evmstore is a generated GoMock package.
package evmstore

import (
	reflect "reflect"

	bundle "github.com/0xsoniclabs/sonic/gossip/blockproc/bundle"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessedBundleStore is a mock of ProcessedBundleStore interface.
type MockProcessedBundleStore struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedBundleStoreMockRecorder
	isgomock struct{}
}

// MockProcessedBundleStoreMockRecorder is the mock recorder for MockProcessedBundleStore.
type MockProcessedBundleStoreMockRecorder struct {
	mock *MockProcessedBundleStore
}

// NewMockProcessedBundleStore creates a new mock instance.
func NewMockProcessedBundleStore(ctrl *gomock.Controller) *MockProcessedBundleStore {
	mock := &MockProcessedBundleStore{ctrl: ctrl}
	mock.recorder = &MockProcessedBundleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedBundleStore) EXPECT() *MockProcessedBundleStoreMockRecorder {
	return m.recorder
}

// AddProcessedBundles mocks base method.
func (m *MockProcessedBundleStore) AddProcessedBundles(block uint64, execInfos map[common.Hash]bundle.PositionInBlock) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProcessedBundles", block, execInfos)
}

// AddProcessedBundles indicates an expected call of AddProcessedBundles.
func (mr *MockProcessedBundleStoreMockRecorder) AddProcessedBundles(block, execInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProcessedBundles", reflect.TypeOf((*MockProcessedBundleStore)(nil).AddProcessedBundles), block, execInfos)
}

// HasBundleRecentlyBeenProcessed mocks base method.
func (m *MockProcessedBundleStore) HasBundleRecentlyBeenProcessed(execPlanHash common.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBundleRecentlyBeenProcessed", execPlanHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasBundleRecentlyBeenProcessed indicates an expected call of HasBundleRecentlyBeenProcessed.
func (mr *MockProcessedBundleStoreMockRecorder) HasBundleRecentlyBeenProcessed(execPlanHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBundleRecentlyBeenProcessed", reflect.TypeOf((*MockProcessedBundleStore)(nil).HasBundleRecentlyBeenProcessed), execPlanHash)
}
