// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source=backend.go -destination=backend_mock.go -package=testapi
//

// Package testapi is a generated GoMock package.
package testapi

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// IsTestOnlyApiEnabled mocks base method.
func (m *MockBackend) IsTestOnlyApiEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTestOnlyApiEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTestOnlyApiEnabled indicates an expected call of IsTestOnlyApiEnabled.
func (mr *MockBackendMockRecorder) IsTestOnlyApiEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTestOnlyApiEnabled", reflect.TypeOf((*MockBackend)(nil).IsTestOnlyApiEnabled))
}

// ProposeTransactions mocks base method.
func (m *MockBackend) ProposeTransactions(txs types.Transactions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposeTransactions", txs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProposeTransactions indicates an expected call of ProposeTransactions.
func (mr *MockBackendMockRecorder) ProposeTransactions(txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeTransactions", reflect.TypeOf((*MockBackend)(nil).ProposeTransactions), txs)
}
